// <auto-generated />
using System;
using BadmintonCourtManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BadmintonCourtManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250705191816_UpdateDB")]
    partial class UpdateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BadmintonCourtManagement.Domain.Entity.Account", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("BadmintonCourtManagement.Domain.Entity.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReportID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalHourBooked")
                        .HasColumnType("float");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("BookingID");

                    b.HasIndex("ReportID");

                    b.HasIndex("UserID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BadmintonCourtManagement.Domain.Entity.Court", b =>
                {
                    b.Property<int>("CourtID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourtID"));

                    b.Property<int>("CourtName")
                        .HasColumnType("int");

                    b.Property<int>("CourtStatus")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("CourtID");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("BadmintonCourtManagement.Domain.Entity.CourtBooking", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.HasKey("BookingId", "CourtId");

                    b.HasIndex("CourtId");

                    b.ToTable("CourtBookings");
                });

            modelBuilder.Entity("BadmintonCourtManagement.Domain.Entity.Feedback", b =>
                {
                    b.Property<int>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackID"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("FeedbackID");

                    b.HasIndex("UserID");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("BadmintonCourtManagement.Domain.Entity.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BadmintonCourtManagement.Domain.Entity.Payment", b =>
                {
                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookingID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("BadmintonCourtManagement.Domain.Entity.Points", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ClaimDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Point")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalRedeem")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("BadmintonCourtManagement.Domain.Entity.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalFreeHour")
                        .HasColumnType("int");

                    b.HasKey("ReportID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("BadmintonCourtManagement.Domain.Entity.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NotificationID")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("NotificationID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("BadmintonCourtManagement.Domain.Entity.Account", b =>
                {
                    b.HasOne("BadmintonCourtManagement.Domain.Entity.User", "User")
                        .WithOne("Account")
                        .HasForeignKey("BadmintonCourtManagement.Domain.Entity.Account", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BadmintonCourtManagement.Domain.Entity.Booking", b =>
                {
                    b.HasOne("BadmintonCourtManagement.Domain.Entity.Report", "Report")
                        .WithMany("Bookings")
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadmintonCourtManagement.Domain.Entity.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BadmintonCourtManagement.Domain.Entity.CourtBooking", b =>
                {
                    b.HasOne("BadmintonCourtManagement.Domain.Entity.Booking", "Booking")
                        .WithMany("courtBookings")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadmintonCourtManagement.Domain.Entity.Court", "Court")
                        .WithMany("courtBookings")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Court");
                });

            modelBuilder.Entity("BadmintonCourtManagement.Domain.Entity.Feedback", b =>
                {
                    b.HasOne("BadmintonCourtManagement.Domain.Entity.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BadmintonCourtManagement.Domain.Entity.Payment", b =>
                {
                    b.HasOne("BadmintonCourtManagement.Domain.Entity.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("BadmintonCourtManagement.Domain.Entity.Payment", "BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BadmintonCourtManagement.Domain.Entity.Points", b =>
                {
                    b.HasOne("BadmintonCourtManagement.Domain.Entity.User", "User")
                        .WithOne("Points")
                        .HasForeignKey("BadmintonCourtManagement.Domain.Entity.Points", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BadmintonCourtManagement.Domain.Entity.User", b =>
                {
                    b.HasOne("BadmintonCourtManagement.Domain.Entity.Notification", "Notification")
                        .WithMany("Users")
                        .HasForeignKey("NotificationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("BadmintonCourtManagement.Domain.Entity.Booking", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();

                    b.Navigation("courtBookings");
                });

            modelBuilder.Entity("BadmintonCourtManagement.Domain.Entity.Court", b =>
                {
                    b.Navigation("courtBookings");
                });

            modelBuilder.Entity("BadmintonCourtManagement.Domain.Entity.Notification", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BadmintonCourtManagement.Domain.Entity.Report", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BadmintonCourtManagement.Domain.Entity.User", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();

                    b.Navigation("Bookings");

                    b.Navigation("Feedbacks");

                    b.Navigation("Points")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
